"""诈醒学集 — 综合能力测评题库（多主题版）

平台定位为「大学生 AI 主题学习与成果展示平台」，测评题库覆盖多主题：
AI 素养、网络安全、心理健康、求职就业、金融素养、学术诚信、个人信息保护、
校园安全、消防安全、交通安全、应急避险（已下线的「反诈安全」主题不纳入）。

题库设计原则：
- 能力维度采用主题无关的中性五维：辨识力 / 判断力 / 应变力 / 实证力 / 协作力
- 每个能力维度至少 6 题，保证 10 题快速测评（每维度 2 题）能覆盖全部维度
- 每个主题至少 2 题，保证标准测评覆盖面
- 部分多选题支持部分得分（score 0.5~1.0）
- difficulty 分三级：低（常识判断）、中等（需要分析）、高（需要推理）
- risk_stage 为展示用阶段标签：识别阶段 / 分析阶段 / 应对阶段 / 复盘阶段
"""

ALL_QUESTIONS = [
    # ── 辨识力（6 题）────────────────────────────────────────────
    {
        "id": "assess-q1",
        "question_type": "single",
        "fraud_type": "AI 素养",
        "ability_dim": "辨识力",
        "risk_stage": "识别阶段",
        "evidence_tags": ["AI 生成内容", "细节异常"],
        "stem": "一篇 AI 生成的推文配图中，人物有六根手指、背景文字扭曲。判断这类内容的首要步骤是？",
        "options": ["A. 直接转发并提醒他人注意", "B. 先核对细节异常，再查证来源与原始出处", "C. 认为图片逼真即可采信", "D. 只看标题就下结论"],
        "correct_answer": "B",
        "explanation": "AI 生成内容常在细节（手指、文字、光影）露出破绽。辨识信息的第一步是发现异常并溯源，而非直接采信或传播。",
        "difficulty": "低",
    },
    {
        "id": "assess-q2",
        "question_type": "single",
        "fraud_type": "网络安全",
        "ability_dim": "辨识力",
        "risk_stage": "识别阶段",
        "evidence_tags": ["钓鱼页面", "域名异常"],
        "stem": "收到「校园邮箱将被停用，请点击链接验证」的邮件，链接域名为 mail-verify-campus.xyz。最明显的风险信号是？",
        "options": ["A. 邮件用了中文", "B. 域名与学校官方域名不符", "C. 邮件有落款", "D. 邮件发送时间在工作日"],
        "correct_answer": "B",
        "explanation": "钓鱼链接通常使用与官方相似的非常规域名（如 .xyz、多级连字符域名）。核对接发件域名是识别钓鱼的第一道防线。",
        "difficulty": "低",
    },
    {
        "id": "assess-q3",
        "question_type": "single",
        "fraud_type": "心理健康",
        "ability_dim": "辨识力",
        "risk_stage": "识别阶段",
        "evidence_tags": ["压力信号", "自我觉察"],
        "stem": "连续两周失眠、注意力下降、对原本感兴趣的事提不起劲。这些信号最可能提示什么？",
        "options": ["A. 只是普通的疲惫，忍一忍就过去", "B. 可能存在持续的心理压力，需要关注和调节", "C. 身体疾病，只能等它自愈", "D. 懒惰的表现，应当自责"],
        "correct_answer": "B",
        "explanation": "持续两周以上的睡眠、兴趣、注意力变化是心理压力的典型信号，及时觉察并主动调节或求助是健康的方式。",
        "difficulty": "低",
    },
    {
        "id": "assess-q4",
        "question_type": "single",
        "fraud_type": "金融素养",
        "ability_dim": "辨识力",
        "risk_stage": "识别阶段",
        "evidence_tags": ["收益承诺", "风险错配"],
        "stem": "某理财产品宣传「保本保息、年化 15%、随存随取」。以下哪个判断最准确？",
        "options": ["A. 收益高又保本，值得入手", "B. 承诺明显超出市场常规水平，涉嫌虚假宣传或高风险", "C. 只要平台有 App 就可信", "D. 朋友也在买就没问题"],
        "correct_answer": "B",
        "explanation": "收益与风险成正比是金融常识，「保本 + 超高收益 + 随时取」三者同时满足的宣传基本可判定为虚假或极高风险。",
        "difficulty": "低",
    },
    {
        "id": "assess-q5",
        "question_type": "single",
        "fraud_type": "个人信息保护",
        "ability_dim": "辨识力",
        "risk_stage": "识别阶段",
        "evidence_tags": ["过度索权", "隐私条款"],
        "stem": "一款手电筒 App 申请读取通讯录、相册和位置权限。辨识风险的关键点是？",
        "options": ["A. App 商店排名靠前就没问题", "B. 权限申请与功能无关，属于过度索权", "C. 安装包小说明安全", "D. 有开屏动画说明制作精良"],
        "correct_answer": "B",
        "explanation": "权限应当与功能匹配。手电筒无需通讯录与位置，过度索权是识别恶意 App 侵犯个人信息的关键信号。",
        "difficulty": "低",
    },

    # ── 判断力（6 题）────────────────────────────────────────────
    {
        "id": "assess-q7",
        "question_type": "single",
        "fraud_type": "AI 素养",
        "ability_dim": "判断力",
        "risk_stage": "分析阶段",
        "evidence_tags": ["信息交叉验证", "来源可靠性"],
        "stem": "社交平台上流传一段「突发新闻」短视频，画面震撼但无媒体来源。判断信息真伪较稳妥的做法是？",
        "options": ["A. 播放量高说明是真的", "B. 查权威媒体是否报道，并对比多个独立信源", "C. 评论区有人说是真的就行", "D. 先转发让更多人帮忙判断"],
        "correct_answer": "B",
        "explanation": "面对 AI 时代海量生成内容，交叉验证独立信源是判断真伪的基本方法；播放量与评论热度不能作为真实性依据。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q8",
        "question_type": "single",
        "fraud_type": "求职就业",
        "ability_dim": "判断力",
        "risk_stage": "分析阶段",
        "evidence_tags": ["培训贷", "包就业承诺"],
        "stem": "某公司称「培训 3 个月包分配高薪工作」，但要求签订 19800 元的培训贷款合同。如何判断这一 offer？",
        "options": ["A. 包分配说明公司有实力，可以签", "B. 「培训贷 + 包就业」组合涉嫌以招聘为名推销贷款，应高度警惕", "C. 只要月供不高就没风险", "D. 先签了再说，违约金以后再算"],
        "correct_answer": "B",
        "explanation": "以录用为条件捆绑培训贷款是典型的求职陷阱：培训质量与就业承诺往往无法兑现，贷款债务却真实存在。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q9",
        "question_type": "single",
        "fraud_type": "学术诚信",
        "ability_dim": "判断力",
        "risk_stage": "分析阶段",
        "evidence_tags": ["AI 代写", "学术规范"],
        "stem": "期末论文截止前，有同学建议「用 AI 全文生成再稍作修改」。从学术规范角度判断，这一做法属于？",
        "options": ["A. 高效利用工具，完全合规", "B. 将 AI 生成内容冒充原创，属于学术不端", "C. 只要查重率低就没问题", "D. 老师看不出来就没事"],
        "correct_answer": "B",
        "explanation": "AI 可用于资料检索、思路启发与语言润色，但将生成内容冒充个人原创提交，违反学术诚信的基本要求。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q10",
        "question_type": "single",
        "fraud_type": "交通安全",
        "ability_dim": "判断力",
        "risk_stage": "分析阶段",
        "evidence_tags": ["骑行安全", "分心驾驶"],
        "stem": "骑电动车去上课时手机响起重要消息。以下哪个判断是正确的？",
        "options": ["A. 边骑边低头看一眼，几秒钟没事", "B. 先靠边停车处理完再继续骑行", "C. 戴上耳机用语音回复，不影响", "D. 加速骑回宿舍再看"],
        "correct_answer": "B",
        "explanation": "骑行中任何分心（看手机、戴耳机）都会显著提高事故风险。正确做法是先停靠安全区域再处理信息。",
        "difficulty": "低",
    },
    {
        "id": "assess-q11",
        "question_type": "multiple",
        "fraud_type": "网络安全",
        "ability_dim": "判断力",
        "risk_stage": "分析阶段",
        "evidence_tags": ["弱口令", "撞库攻击"],
        "stem": "以下哪些密码习惯会显著增加账号被盗风险？（多选）",
        "options": ["A. 多个平台使用同一个密码", "B. 密码为生日或 123456", "C. 开启了两步验证", "D. 在公共电脑上勾选「记住密码」"],
        "correct_answer": ["A", "B", "D"],
        "explanation": "重复密码易被撞库、简单密码易被穷举、公共设备记住密码易被后续使用者利用；两步验证则是保护措施。",
        "difficulty": "中等",
    },

    # ── 应变力（6 题）────────────────────────────────────────────
    {
        "id": "assess-q13",
        "question_type": "single",
        "fraud_type": "应急避险",
        "ability_dim": "应变力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["现场急救", "呼救优先"],
        "stem": "在校道上看到有人突然倒地、无意识无呼吸。你的第一反应应该是？",
        "options": ["A. 立即大声呼救并拨打 120，同时请求取来 AED", "B. 先拍视频发群里问怎么办", "C. 等其他人来处理", "D. 马上喂水喂药"],
        "correct_answer": "A",
        "explanation": "心脏骤停的黄金抢救时间只有 4 分钟。第一反应应是呼救、拨打 120 并获取 AED，再配合胸外按压，而非围观等待。",
        "difficulty": "低",
    },
    {
        "id": "assess-q14",
        "question_type": "single",
        "fraud_type": "消防安全",
        "ability_dim": "应变力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["火场逃生", "低姿撤离"],
        "stem": "宿舍楼夜间火警响起，楼道有烟。撤离时的正确做法是？",
        "options": ["A. 乘电梯最快下楼", "B. 用湿毛巾捂口鼻、低姿沿疏散通道撤离", "C. 回房间收拾贵重物品再走", "D. 躲进卫生间等烟散"],
        "correct_answer": "B",
        "explanation": "火场逃生禁止乘电梯（断电被困）；浓烟上浮，应低姿前进并以湿毛巾捂口鼻，沿疏散指示快速撤离，不为财物折返。",
        "difficulty": "低",
    },
    {
        "id": "assess-q15",
        "question_type": "single",
        "fraud_type": "心理健康",
        "ability_dim": "应变力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["情绪急救", "求助渠道"],
        "stem": "室友连续几天情绪崩溃、说「撑不下去了」。你当下最合适的做法是？",
        "options": ["A. 告诉他「想开点，大家都这样」", "B. 陪伴倾听、不评判，并陪他预约学校心理中心", "C. 替他保密，谁也不告诉", "D. 给他看我推荐的搞笑视频转移注意"],
        "correct_answer": "B",
        "explanation": "面对强烈的心理危机信号，有效做法是稳定陪伴、认真倾听，并协助连接专业资源（心理中心、辅导员）。「想开点」式的安慰容易造成二次伤害。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q16",
        "question_type": "single",
        "fraud_type": "个人信息保护",
        "ability_dim": "应变力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["账号盗用", "止损动作"],
        "stem": "发现自己社交账号异地登录、疑似被盗。应优先采取的动作是？",
        "options": ["A. 在朋友圈发澄清声明就算处理完", "B. 立即修改密码、下线所有设备、开启两步验证", "C. 注销手机号换新号", "D. 等几天看对方会不会自己退出"],
        "correct_answer": "B",
        "explanation": "账号被盗的止损顺序：改密码 → 踢出异常会话 → 开启二次验证 → 再通知亲友防范冒用。仅发声明无法阻断盗用。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q18",
        "question_type": "single",
        "fraud_type": "校园安全",
        "ability_dim": "应变力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["夜间出行", "安全路线"],
        "stem": "晚自习结束较晚，需要独自返回宿舍。以下哪种安排最稳妥？",
        "options": ["A. 抄小路近道尽快回去", "B. 结伴同行或走照明良好的主干道，并分享实时位置给室友", "C. 戴上耳机快走，听不到周围更专注", "D. 边走边刷手机缓解紧张"],
        "correct_answer": "B",
        "explanation": "夜间出行安全三要素：结伴、走亮路、有人知晓行程。小路、耳机与低头刷手机都会削弱对环境的感知与应变能力。",
        "difficulty": "低",
    },

    # ── 实证力（6 题）────────────────────────────────────────────
    {
        "id": "assess-q19",
        "question_type": "single",
        "fraud_type": "学术诚信",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["引用规范", "资料溯源"],
        "stem": "写课程论文引用网络文章时，规范的实证做法是？",
        "options": ["A. 复制观点后不标注来源", "B. 记录作者、标题、网址与访问日期，按引用格式标注", "C. 只在文末统一写「来源于网络」", "D. 改几个词就不算引用"],
        "correct_answer": "B",
        "explanation": "可溯源是学术实证的基本要求：完整记录来源信息（作者、标题、URL、访问日期）并规范标注，既尊重原创也便于核查。",
        "difficulty": "低",
    },
    {
        "id": "assess-q20",
        "question_type": "single",
        "fraud_type": "AI 素养",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["AI 幻觉", "信息核验"],
        "stem": "用 AI 助手写文献综述时，它给出了几条带作者与年份的「文献」。实证角度的稳妥做法是？",
        "options": ["A. AI 给出的文献直接引用", "B. 逐条在学术数据库检索核实，不存在的文献不引用", "C. 只要格式规范就可以用", "D. 引用一半核实一半"],
        "correct_answer": "B",
        "explanation": "AI 存在「幻觉」，可能编造看似规范的文献。所有引用必须经数据库逐条核实，这是 AI 辅助学习的基本纪律。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q21",
        "question_type": "single",
        "fraud_type": "金融素养",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["记账习惯", "数据核对"],
        "stem": "月底发现生活费超支却不明白钱花在哪。最有效的实证方法是？",
        "options": ["A. 凭印象估计各项支出", "B. 导出支付账单逐笔归类，找出前三大支出项", "C. 下个月直接少花一半", "D. 询问同学大家都花多少"],
        "correct_answer": "B",
        "explanation": "理财改善始于数据：以账单为证据逐笔归类复盘，定位真实的支出结构，再针对性调整，比印象式估计可靠得多。",
        "difficulty": "低",
    },
    {
        "id": "assess-q22",
        "question_type": "multiple",
        "fraud_type": "求职就业",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["三方协议", "权益条款"],
        "stem": "签署三方协议前，以下哪些属于必要的实证核查？（多选）",
        "options": ["A. 在企业信用公示系统查公司经营状态", "B. 逐条核对违约金、试用期、薪资构成条款", "C. 只看 HR 口头承诺", "D. 与学长学姐或就业指导老师沟通该公司的口碑"],
        "correct_answer": ["A", "B", "D"],
        "explanation": "签约前的实证功课：查企业工商信息、逐条核对书面条款、收集多方口碑。口头承诺缺乏凭证，不能替代合同文本。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q23",
        "question_type": "single",
        "fraud_type": "网络安全",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["官方渠道", "补丁更新"],
        "stem": "电脑弹出「检测到病毒，立即下载杀毒工具」的窗口。具有实证意识的正确做法是？",
        "options": ["A. 立即点击下载，越快越好", "B. 关闭弹窗，从操作系统自带的安全中心或官网渠道核实与更新", "C. 把弹窗截图发到群里让大家下载", "D. 忽略一切系统提示，包括真实的安全更新"],
        "correct_answer": "B",
        "explanation": "弹窗诱导下载常为仿冒软件。实证做法是关闭诱导入口，转向系统官方安全中心核实；同时也不应因噎废食忽略正规更新。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q24",
        "question_type": "single",
        "fraud_type": "应急避险",
        "ability_dim": "实证力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["权威信源", "预警核验"],
        "stem": "群里流传「今晚将有极端天气停课」的截图，但无出处。核实的正确渠道是？",
        "options": ["A. 转发班级群互相确认", "B. 查看学校官方通知与气象部门官方预警", "C. 看到的人多就是真的", "D. 按截图内容做准备即可，宁可信其有"],
        "correct_answer": "B",
        "explanation": "涉及安全的决策必须以官方权威信源为证据：学校官方通知、气象部门预警。转发链上的截图无法作为决策依据。",
        "difficulty": "低",
    },

    # ── 协作力（6 题）────────────────────────────────────────────
    {
        "id": "assess-q25",
        "question_type": "single",
        "fraud_type": "校园安全",
        "ability_dim": "协作力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["群防群治", "信息共享"],
        "stem": "在校园里发现一处路灯损坏的僻静路段。发挥协作精神的合适做法是？",
        "options": ["A. 与自己无关，绕开走就行", "B. 通过学校后勤/保卫处报修渠道上报，并提醒常走该路的同学", "C. 发朋友圈吐槽学校", "D. 等别人总会报的"],
        "correct_answer": "B",
        "explanation": "校园安全共建依赖每个人都参与：向职能部门反馈隐患，并在同伴间共享提醒，把个体观察转化为集体防护。",
        "difficulty": "低",
    },
    {
        "id": "assess-q26",
        "question_type": "single",
        "fraud_type": "心理健康",
        "ability_dim": "协作力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["朋辈支持", "专业转介"],
        "stem": "小组学习中一位成员因家庭变故频繁缺席，任务进度受阻。组长的协作式处理方式是？",
        "options": ["A. 直接向老师告状要求换人", "B. 私下关心了解情况，协商任务分工调整，必要时陪同联系辅导员", "C. 在组群里公开批评他拖后腿", "D. 默默替他做完所有任务"],
        "correct_answer": "B",
        "explanation": "协作力体现在兼顾任务与成员：主动沟通、灵活调整分工、连接支持资源；公开指责或无条件包办都不是可持续的协作。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q27",
        "question_type": "multiple",
        "fraud_type": "AI 素养",
        "ability_dim": "协作力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["小组共创", "AI 使用规范"],
        "stem": "小组用 AI 工具协作完成课程展示时，规范的做法包括？（多选）",
        "options": ["A. 明确分工并记录各自贡献", "B. 在作品中说明 AI 参与的部分与使用方式", "C. 让 AI 全文代写并由一人提交", "D. 组内互相核查 AI 生成内容的准确性"],
        "correct_answer": ["A", "B", "D"],
        "explanation": "AI 时代的协作规范：分工透明、贡献可溯、AI 使用披露、内容交叉核验。全文代写冒充原创既违反诚信也丧失学习价值。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q28",
        "question_type": "single",
        "fraud_type": "消防安全",
        "ability_dim": "协作力",
        "risk_stage": "应对阶段",
        "evidence_tags": ["疏散引导", "互助撤离"],
        "stem": "消防演练中你被任命为楼层疏散引导员。演练时发现一位同学行动不便。你的协作职责是？",
        "options": ["A. 独自快速撤离，不管他人", "B. 协助其按预案路线撤离，并及时向楼层负责人报告情况", "C. 让他自己想办法跟上", "D. 背起他冲刺下楼以免担责"],
        "correct_answer": "B",
        "explanation": "疏散引导员的协作职责是按预案协助与上报，既不弃人不顾，也不逞英雄式冒险（如盲目背负冲刺），保证信息通畅与整体秩序。",
        "difficulty": "中等",
    },
    {
        "id": "assess-q29",
        "question_type": "single",
        "fraud_type": "求职就业",
        "ability_dim": "协作力",
        "risk_stage": "复盘阶段",
        "evidence_tags": ["经验共享", "信息互助"],
        "stem": "你识破了一个「交钱包入职」的假招聘。比较有协作价值的做法是？",
        "options": ["A. 自己避坑就行，多一事不如少一事", "B. 在班级求职群分享套路特征与核实方法，提醒大家防范", "C. 把招聘方联系方式发群里让大家去骂", "D. 编成段子发到网上娱乐"],
        "correct_answer": "B",
        "explanation": "求职信息的互助共享能有效放大个体经验的价值：分享可识别的套路特征与核实方法，帮助同伴建立判断力（而非网络攻击）。",
        "difficulty": "低",
    },
]
