"""add_phase1_tables

Revision ID: 04302bbf2b3d
Revises: 3b3c8a7b10d2
Create Date: 2026-07-22 17:09:39.277641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04302bbf2b3d'
down_revision: Union[str, Sequence[str], None] = '3b3c8a7b10d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('weak_dimensions_json', sa.Text(), nullable=False),
    sa.Column('weak_types_json', sa.Text(), nullable=False),
    sa.Column('total_growth', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(), nullable=False),
    sa.Column('trigger_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_snapshots_created_at'), 'ability_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_ability_snapshots_owner_id'), 'ability_snapshots', ['owner_id'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('completed_questions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_owner_id'), 'assessment_sessions', ['owner_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_key', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('design_rationale', sa.Text(), nullable=False),
    sa.Column('min_model', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_key'), 'prompt_versions', ['prompt_key'], unique=False)
    op.create_table('question_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('ability_dim', sa.String(), nullable=False),
    sa.Column('risk_stage', sa.String(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_answer_json', sa.Text(), nullable=False),
    sa.Column('evidence_tags_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_metadata_ability_dim'), 'question_metadata', ['ability_dim'], unique=False)
    op.create_index(op.f('ix_question_metadata_fraud_type'), 'question_metadata', ['fraud_type'], unique=False)
    op.create_table('risk_test_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('expected_evidence_json', sa.Text(), nullable=False),
    sa.Column('risk_stage', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('dataset_label', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_test_samples_dataset_label'), 'risk_test_samples', ['dataset_label'], unique=False)
    op.create_index(op.f('ix_risk_test_samples_fraud_type'), 'risk_test_samples', ['fraud_type'], unique=False)
    op.create_table('scenario_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opening_message', sa.Text(), nullable=False),
    sa.Column('initial_state', sa.String(), nullable=False),
    sa.Column('key_evidence_tags_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_templates_fraud_type'), 'scenario_templates', ['fraud_type'], unique=True)
    op.create_table('wrong_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_stem', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('ability_dim', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('retrain_status', sa.String(), nullable=False),
    sa.Column('retrain_count', sa.Integer(), nullable=False),
    sa.Column('last_retrain_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrong_items_created_at'), 'wrong_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_wrong_items_fraud_type'), 'wrong_items', ['fraud_type'], unique=False)
    op.create_index(op.f('ix_wrong_items_owner_id'), 'wrong_items', ['owner_id'], unique=False)
    op.create_table('ability_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('dim_key', sa.String(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=False),
    sa.Column('score_after', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ability_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_events_owner_id'), 'ability_events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ability_events_snapshot_id'), 'ability_events', ['snapshot_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('ability_dim', sa.String(), nullable=False),
    sa.Column('risk_stage', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_owner_id'), 'assessment_answers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_session_id'), 'assessment_answers', ['session_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('evidence_tag', sa.String(), nullable=False),
    sa.Column('identified', sa.Boolean(), nullable=False),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scenario_training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_owner_id'), 'evidence_records', ['owner_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_session_id'), 'evidence_records', ['session_id'], unique=False)
    op.create_table('retrain_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('wrong_item_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('variant_question_id', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wrong_item_id'], ['wrong_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrain_schedules_owner_id'), 'retrain_schedules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_retrain_schedules_scheduled_at'), 'retrain_schedules', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_retrain_schedules_wrong_item_id'), 'retrain_schedules', ['wrong_item_id'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('identified_evidence_json', sa.Text(), nullable=False),
    sa.Column('missed_evidence_json', sa.Text(), nullable=False),
    sa.Column('correct_behaviors_json', sa.Text(), nullable=False),
    sa.Column('risk_behaviors_json', sa.Text(), nullable=False),
    sa.Column('recognition_score', sa.Float(), nullable=False),
    sa.Column('judgment_score', sa.Float(), nullable=False),
    sa.Column('response_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('help_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('next_suggestions_json', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scenario_training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_owner_id'), 'review_reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_review_reports_session_id'), 'review_reports', ['session_id'], unique=False)
    op.create_table('scenario_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('correct_triggers_json', sa.Text(), nullable=False),
    sa.Column('hesitation_triggers_json', sa.Text(), nullable=False),
    sa.Column('wrong_triggers_json', sa.Text(), nullable=False),
    sa.Column('next_state', sa.String(), nullable=True),
    sa.Column('evidence_hints_json', sa.Text(), nullable=False),
    sa.Column('correct_strategy', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scenario_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_turns_template_id'), 'scenario_turns', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_turns_template_id'), table_name='scenario_turns')
    op.drop_table('scenario_turns')
    op.drop_index(op.f('ix_review_reports_session_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_owner_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_retrain_schedules_wrong_item_id'), table_name='retrain_schedules')
    op.drop_index(op.f('ix_retrain_schedules_scheduled_at'), table_name='retrain_schedules')
    op.drop_index(op.f('ix_retrain_schedules_owner_id'), table_name='retrain_schedules')
    op.drop_table('retrain_schedules')
    op.drop_index(op.f('ix_evidence_records_session_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_owner_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_assessment_answers_session_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_owner_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_ability_events_snapshot_id'), table_name='ability_events')
    op.drop_index(op.f('ix_ability_events_owner_id'), table_name='ability_events')
    op.drop_table('ability_events')
    op.drop_index(op.f('ix_wrong_items_owner_id'), table_name='wrong_items')
    op.drop_index(op.f('ix_wrong_items_fraud_type'), table_name='wrong_items')
    op.drop_index(op.f('ix_wrong_items_created_at'), table_name='wrong_items')
    op.drop_table('wrong_items')
    op.drop_index(op.f('ix_scenario_templates_fraud_type'), table_name='scenario_templates')
    op.drop_table('scenario_templates')
    op.drop_index(op.f('ix_risk_test_samples_fraud_type'), table_name='risk_test_samples')
    op.drop_index(op.f('ix_risk_test_samples_dataset_label'), table_name='risk_test_samples')
    op.drop_table('risk_test_samples')
    op.drop_index(op.f('ix_question_metadata_fraud_type'), table_name='question_metadata')
    op.drop_index(op.f('ix_question_metadata_ability_dim'), table_name='question_metadata')
    op.drop_table('question_metadata')
    op.drop_index(op.f('ix_prompt_versions_prompt_key'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_assessment_sessions_owner_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_ability_snapshots_owner_id'), table_name='ability_snapshots')
    op.drop_index(op.f('ix_ability_snapshots_created_at'), table_name='ability_snapshots')
    op.drop_table('ability_snapshots')
    # ### end Alembic commands ###
